### ISSUE TITLE
context path hard coded in sparkl

### ISSUE THREAD

**Issue by volvicoasis** [webdetails/sparkl#38]
Actually, if you run pentaho ba server version 5.3 with a context path different from pentaho (ex : http://ipserver:8080/myapp and not http://ipserver:8080/pentaho), sparkl won't work at all.
After changing all matchin occurence to our current conf, sparkl is working like a charm.

You can found how may file we need to modify in this plugin to work with sparkl :
[-----> sparkl]$ grep -R "pentaho/" *
build.xml: <get src="http://127.0.0.1:8080/pentaho/Publish?publish=now&amp;class=org.pentaho.platform.plugin.services.pluginmgr.PluginAdapter&amp;userid=${plugin.local.install.user}&amp;password=${plugin.local.install.pass}"
dashboards/admin/variableInfo.cdfde: "value": "/pentaho/api/repos/sparkl/static/custom/js/sparkl.js",
dashboards/admin/variableInfo.cdfde: "value": "/pentaho/api/repos/sparkl/static/custom/css/sparkl.css",
documentation/spec.md:* _Feedback (email)_: sends email to pentaho/ctools/plugin-author with
documentation/spec.md:* _Report a Bug (email)_: sends email to pentaho/ctools/plugin-author
documentation/spec.md: * Description: pack plugin and open email default application with zip file already attached and author/pentaho/ctools email address already inserted
Fichier binaire lib/cpf-pentaho5-5.3.0.0-213.jar concordant
resources/components/SparklCards/component.js: imgSrc = Dashboards.getWebAppPath() + '/pentaho/api/repos/' + pluginId + '/static/system/img/pluginLogo___.png';
resources/styles/sparkl.html: <link rel="stylesheet" type="text/css" href="/pentaho/api/repos/sparkl/static/custom/css/sparklTemplate.css" />
resources/styles/sparkl.html: <a class='sparklLogo' href='/pentaho/plugin/sparkl/api/main'></a>
resources/styles/cpk.html: <link rel="stylesheet" type="text/css" href="/pentaho/api/repos/sparkl/static/system/css/cpk.css" />
stub/build.xml.token: <get src="http://127.0.0.1:8080/pentaho/Publish?publish=now&amp;class=org.pentaho.platform.plugin.services.pluginmgr.PluginAdapter&amp;userid=${plugin.local.install.user}&amp;password=${plugin.local.install.pass}"

**Comment by pamval** [comment]
Hi, Jacques.

Thanks for the feedback. Could you please open an issue at http://jira.pentaho.com/browse/SPARKL ?
That's what we use for bug tracking.

Thanks!

**Comment by volvicoasis** [comment]
Done ! http://jira.pentaho.com/browse/SPARKL-148
